#!/usr/bin/env python

import cv2
faces=[]
face_cascade=cv2.CascadeClassifier("/home/nidhi/Desktop/python/face_detector/haarcascade_frontalface_default.xml")
cap=cv2.VideoCapture(0)

while cap.isOpened():
    _,img =cap.read()
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces=face_cascade.detectMultiScale(gray, 1.05, 4, 0)
    
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),3)

        cv2.imshow('output',img)
    if cv2.waitKey(1) & 0xFF ==ord('q'):
        break
      
      
          
          
cap.release()
